 
stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "s6-apache"
  IMAGE_TAG: "latest"
  GITHUB_PROJECT: "p42/s6-centos-apache-docker.git"

before_script:
  - docker info

build-master:
  tags:
    - ovirt
    - docker
  stage: build
  script:
    - docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .
  only:
    - master

test-master:
  tags:
    - ovirt
    - docker
  stage: test
  script:
    - docker run --rm "${IMAGE_NAME}:${IMAGE_TAG}" /bin/bash /ci_tests/master_test.sh
  only:
    - master

# test:
  # tags:
  #   - ovirt
  #   - docker
#   stage: test
#   script:
#     - docker run --rm "${IMAGE_NAME}:${IMAGE_TAG}" /bin/true
#   except:
#     - master

build:
  tags:
    - ovirt
    - docker
  stage: build
  script:
    - docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .
  except:
    - master

deploy_to_github:
  tags:
    - ovirt
    - docker
  stage: deploy
  script:
    - git push git@github.com:${GITHUB_PROJECT} master
  only:
    - master

deploy_tags_to_github:
  tags:
    - ovirt
    - docker
  stage: deploy
  script:
    - git push git@github.com:${GITHUB_PROJECT} master --tags
  only:
    - tags
