 
stages:
  # - build
  # - test
  - deploy

variables:
  IMAGE_NAME: "s6-apache"
  IMAGE_TAG: "latest"
  # GITHUB_PROJECT: "p42/s6-centos-apache-docker.git"
  GITHUB_PROJECT: "p42/centos-apache-docker.git"

before_script:
  - docker info

# build-master:
#   tags:
#     - ovirt
#     - docker
#   stage: build
#   script:
#     - docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .
#   only:
#     - master

# test-master:
#   tags:
#     - ovirt
#     - docker
#   stage: test
#   script:
#     - docker run -e "HTML_DESTINATION=localhost/index.html" -e "PHP_DESTINATION=localhost/test.php" --rm "${IMAGE_NAME}:${IMAGE_TAG}" /ci_tests/run_tests apache
#   only:
#     - master

# # test:
#   # tags:
#   #   - ovirt
#   #   - docker
# #   stage: test
# #   script:
# #     - docker run -e "HTML_DESTINATION=localhost/index.html" -e "PHP_DESTINATION=localhost/test.php" --rm "${IMAGE_NAME}:${IMAGE_TAG}" /ci_tests/run_tests apache
# #   except:
# #     - master

# build:
#   tags:
#     - ovirt
#     - docker
#   stage: build
#   script:
#     - docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .
#   except:
#     - master

deploy_to_github:
  tags:
    # - ovirt
    - docker
  stage: deploy
  script:
    - echo "Executing script git push git@github.com:${GITHUB_PROJECT} master"
    - git push git@github.com:${GITHUB_PROJECT} master
  only:
    - master

deploy_tags_to_github:
  tags:
    # - ovirt
    - docker
  stage: deploy
  script:
    - git push git@github.com:${GITHUB_PROJECT} master --tags
  only:
    - tags
